FROM localhost/librenms:latest

ENV LIBRENMS_PATH="/opt/librenms" \
    LIBRENMS_DOCKER="1" \
    PUID="1000" \
    PGID="1000" \
    S6_LOGGING="0" \
    S6_READ_ONLY_ROOT="1"

RUN /usr/bin/container-prep-user
USER librenms

# Taken verbatim from the upstream image; not modified
EXPOSE 8000 514 514/udp 162 162/udp

ENTRYPOINT [ "/init" ]
